### ISSUE TITLE
Wrong user selected when GH username changed

### ISSUE THREAD

**Issue by southgate** [boxen/boxen-web#66]
I originally auth'ed to boxen-web using my old username which has since been changed.  Upon auth'ing with my current user, `script.sh` was still being rendered with my old username.  

I'm not totally clear on the issue - I thought at first it was [`User#first_and_create`](https://github.com/boxen/boxen-web/blob/a16f6565cefddd736559807a87d442638c7569bb/app/controllers/auth_controller.rb#L6-L9) but I'd assume that my new login, `southgate`, would be created and `user` set to it.

**Comment by mikemcquaid** [comment]
@southgate can you still reproduce this? At a guess it may be a caching issue.

**Comment by southgate** [comment]
@mikemcquaid no sir. Let's go with caching issue!

**Comment by mikemcquaid** [comment]
@southgate Thanks for checking :sparkles:
