### ISSUE TITLE
Question on boxen-web

### ISSUE THREAD

**Issue by femee24** [boxen/boxen-web#77]
is it possible to use boxen without enabling filevault?

**Comment by Tomohiro** [comment]
Use `--no-fde` option like this `boxen --no-fde`.

**Comment by femee24** [comment]
yah thank you..
but
is it also possible to use boxen-web without enabling filevault?

**Comment by Tomohiro** [comment]
Fork this repository and customize [script template](https://github.com/boxen/boxen-web/blob/45049db61c370f97807b136445450c256c2fda97/app/views/splash/script.sh.erb#L134).
But I know this way is hard to common use for team...

**Comment by femee24** [comment]
Thank you for that :)
