### ISSUE TITLE
Can't run script/server 

### ISSUE THREAD

**Issue by Gilroy24** [boxen/boxen-web#91]
it gives me an error: 
`config/unicorn/development.rb:1:in `reload': undefined method `+' for nil:NilClass (NoMethodError)`

**Comment by jacobbednarz** [comment]
What version of Ruby are you running? Are you running on the latest `boxen-web`?

**Comment by Gilroy24** [comment]
Yes, i recently forked your boxen-web, whenever i run script/server in ~/src/boxen-web/ it shows that error

**Comment by jacobbednarz** [comment]
Can you please provide the output from the following commands from inside of the `~/src/boxen-web` directory?

```
ruby -v
```

```
gem list --local
```

**Comment by Gilroy24** [comment]
Here are the output
```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]

```
```
gem list --local
*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.12.5)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
pg (0.18.4)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
test-unit (3.1.5)
```

**Comment by jacobbednarz** [comment]
Looks like you are missing the required gems. Try running the steps mentioned [in the README](https://github.com/boxen/boxen-web#development).

**Comment by Gilroy24** [comment]
@jacobbednarz what should it looks like when it has all the gems? i've tried using `gem update bundler`, `gem install bundler`, and running the `script/bootstrap` command but nothing prompts. What's the proper way of gathering required gems? When i get to the step of script/server the same error prompts. Thanks

**Comment by jacobbednarz** [comment]
Something along the lines of this:

```
$ gem list --local

*** LOCAL GEMS ***

albino (1.3.3)
bigdecimal (1.2.4)
bundler (1.11.2, 1.6.9)
chunky_png (1.3.4)
classifier (1.3.4)
coderay (1.1.0)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
directory_watcher (1.5.1)
fast-stemmer (1.0.2)
ffi (1.9.8)
haml (4.0.6)
io-console (0.4.3)
jekyll (0.11.2)
json (1.8.1)
kramdown (0.14.2)
liquid (2.6.2)
maruku (0.7.2)
method_source (0.8.2)
minitest (4.7.5)
multi_json (1.11.0)
posix-spawn (0.3.11)
pry (0.10.1)
psych (2.0.5)
pygments.rb (0.6.3)
rack (1.6.0)
rack-protection (1.5.3)
rake (10.4.2, 10.1.0)
rb-fsevent (0.9.4)
rb-inotify (0.9.5)
rdiscount (2.1.8)
rdoc (4.1.0)
RedCloth (4.2.9)
rubypants (0.2.0)
sass (3.4.13)
sinatra (1.4.6)
slop (3.6.0)
stringex (2.5.2)
susy (1.0.3)
test-unit (2.1.6.0)
tilt (2.0.1)
yajl-ruby (1.2.1)
```

Try manually installing it by running `cd ~/src/boxen-web && bundle install`

**Comment by Gilroy24** [comment]
@jacobbednarz I've already resolved the problem by installing fresh boxen and boxen-web in my machine, updated couple of gems, carefully bootstrapping now it works fine, I'm gonna proceed now on pushing my boxen-web into heroku hope it won't be that slow like pushing a new boxen branch in our private boxen. Thank you very much for your time sir @jacobbednarz

**Comment by jacobbednarz** [comment]
👍 great to hear!
